---
- name: Ensure FASTBuild cache directory exists
  become: true
  become_user: "{{ fastbuild_cache_owner }}"
  win_file:
    path: "{{ fastbuild_cache_dir }}"
    state: directory

- name: Set FASTBuild cache path environment variable
  win_environment:
    name: "FASTBUILD_CACHE_PATH"
    value: "{{ fastbuild_cache_dir }}"
    level: machine
