---
- name: Create temporary directory for downloads
  win_tempfile:
    state: directory
    prefix: fastbuild
  register: fastbuild_temp_dir

- name: Download FASTBuild zipfile
  win_get_url:
    url: "{{ fastbuild_url_base }}/v{{ fastbuild_version }}/FASTBuild-Windows-{{ fastbuild_arch }}-v{{ fastbuild_version }}.zip"
    dest: "{{ fastbuild_temp_dir.path }}/FASTBuild.zip"

- name: Unzip FASTBuild archive
  win_unzip:
    src: "{{ fastbuild_temp_dir.path }}/FASTBuild.zip"
    dest: "{{ fastbuild_temp_dir.path }}"
    delete_archive: true

- name: Install FASTBuild executables
  win_shell: "Move-Item -Force -Path '{{ fastbuild_temp_dir.path }}\\{{ item }}' \
    '{{ fastbuild_path_win }}'"
  with_items:
    - FBuild.exe
    - FBuildWorker.exe

- name: Allow all users to run FASTBuild executables
  win_acl:
    path: "{{ fastbuild_path_win }}\\{{ item }}"
    user: BUILTIN\Users
    rights: ReadAndExecute
    type: allow
  with_items:
    - FBuild.exe
    - FBuildWorker.exe
